name: React app deployment
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run : npm i
      working-directory: ./app
      shell: bash
    - run : npm ci
      working-directory: ./app
      shell: bash
    - run : npm run build
      working-directory: ./app
      shell: bash
    - run : git config user.name github-actions
      working-directory: ./app
      shell: bash
    - run : git config user.email github-actions@github.com
      working-directory: ./app
      shell: bash
    - run : git --work-tree build add --all
      working-directory: ./app
      shell: bash
    - run : git commit -m "Automatic Deploy action run by github-actions"
      working-directory: ./app
      shell: bash
    - run : git push origin HEAD:gh-pages --force
      working-directory: ./app
      shell: bash
